### ISSUE TITLE
ignore text inside <video> tags

### ISSUE THREAD

**Issue by snarfed** [Alir3z4/html2text#112]
first of all, thanks for maintaining html2text, it's great!

one feature request: an option to drop text inside `<video>` tags would be nice. according to HTML5, if a user agent supports the video tag, then it must ignore the content inside, since that's only for browsers / UAs that don't support the video tag. background in snarfed/bridgy#612.

thanks in advance!

**Comment by Alir3z4** [comment]
Thank you for your kind feedback, indeed html2text is great.

As for the feature request,you mean dropping a text like the video URL or video name instead of <video> ?

What html2text is trying to do, simply convert the HTML into a clean text that can be considered as `Markdown` as well, and thing is how we gonna transfer the text back into HTML again with markdown implementations? does any markdown implementations support videos ?

@theSage21 your thoughts on this ?

**Comment by theSage21** [comment]
@snarfed  dropping the text might be justified in lost of use cases but I am against adding another option for this. Mainly because of the existance of `out` which can pretty much handle this job. I would suggest that you have a look at the `out` argument of the `HTML2Text` constructor.
