### ISSUE TITLE
Text after list handled incorrectly

### ISSUE THREAD

**Issue by dairiki** [Alir3z4/html2text#119]
- Version 2016.1.8

When fed this input:
```html
<ul><li>item</li></ul>
text
```
this markdown is produced
```markdown
  * item
text
```
which renders as

  * item
text

The markdown should have, I think, a blank line after the list, e.g.
```markdown
  * item

text
```

**Comment by theSage21** [comment]
Glad to see that the templates are working. :smile:   
I don't know about this. I suppose it depends on the renderer how the MD is rendered but then in all the popular places where MD is used practices do coincide with what you say. I could think of no case where this would be bad other than changing known behaviour.

@Alir3z4 if you agree I'll implement as soon as I am free.

**Comment by Alir3z4** [comment]
@theSage21 yeah, I found out the moment I looked at the issue description.

I checked what @dairiki has described here and the expected behavior should be implemented. Without that blank line after list, the text would be considered as a member or included in the list as well, which it should not be like this.

My vote for implementing/fix such feature/bug.
@theSage21 Would be great to see your patch.

**Comment by theSage21** [comment]
@Alir3z4 This is causing 4 tests to fail. Should I rewrite them?

**Comment by theSage21** [comment]
@dairiki This will be difficult to implement for Google Docs styles. Will that be ok?

**Comment by theSage21** [comment]
@Alir3z4 check it out and pull when you can.

**Comment by Alir3z4** [comment]
@theSage21 Great work on the patch.
I left some comments for on the pull-request ;)

**Comment by dairiki** [comment]
@theSage21 Thank you!

It doesn't bother me personally (at the moment, at least) that this is still broken for google docs.
