### ISSUE TITLE
EOF in middle of entity or char ref

### ISSUE THREAD

**Issue by matiskay** [Alir3z4/html2text#121]
Hi, I got an `EOF in middle of entity or char ref` error. I remove `&` and it fixed the problem. Is there a way to fix this problem without removing `&`?

- Version: 2015.6.21
- Test script
```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import html2text

text = u'Forma\xe7\xe3o : Curso t\xe9cnico na \xe1rea mec\xe2nica \r\nIngl\xeas : Avan\xe7ado \r\nConhecimento em modelagem 3 D e desenho 2D, PLM , GD&T'

html_conv = html2text.HTML2Text(bodywidth=None)
html_conv.handle(text)
```

```
Traceback (most recent call last):
  File "sample.py", line 8, in <module>
    html_conv.handle(text)
  File "/Users/matiskay/.envs/scrapy/lib/python2.7/site-packages/html2text/__init__.py", line 129, in handle
    return self.optwrap(self.close())
  File "/Users/matiskay/.envs/scrapy/lib/python2.7/site-packages/html2text/__init__.py", line 137, in close
    HTMLParser.HTMLParser.close(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 121, in close
    self.goahead(1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 216, in goahead
    self.error("EOF in middle of entity or char ref")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 124, in error
    raise HTMLParseError(message, self.getpos())
HTMLParser.HTMLParseError: EOF in middle of entity or char ref, at line 3, column 53
```

**Comment by theSage21** [comment]
This issue is only arising on Py2.x when I test it with the version you have provided.  
This is a known bug in the Python `HTMLParser.py`. Read about it [here](https://bugs.python.org/issue445196). I would suggest cleaning the HTML (removing the &) or switching Python versions if possible.  
I would favour switching Python versions.

Since this is not a direct `html2text` bug I'm in favour of closing this. @matiskay @Alir3z4 agree?

**Comment by matiskay** [comment]
I agree.

**Comment by Alir3z4** [comment]
Sad to see something like:
```
In [1]: print u'Forma\xe7\xe3o : Curso t\xe9cnico na \xe1rea mec\xe2nica \r\nIngl\xeas : Avan\xe7ado \r\nConhecimento em modelagem 3 D e desenho 2D, PLM , GD&T'
Formação : Curso técnico na área mecânica 
Inglês : Avançado 
Conhecimento em modelagem 3 D e desenho 2D, PLM , GD&T

In [2]: 
```
is causing issues, the best would be I guess handle the issue outside of the html2text scope and do the exception handling that way.

However, if you're doing lots of `html2text.handle` at the time, like batch processing, that exception handling would cause you bleeding in your performance, since python try;except are slow.

If you're going to stay on that specific versions of python, make sure to clean-up the html before getting   hit.

Also I've set this issue as `wont-fix`.

**Comment by theSage21** [comment]
@Alir3z4 This is not a `html2text` issue.

**Comment by matiskay** [comment]
@theSage21 and @Alir3z4, thank you for your help. I'm cleaning the text before using `html2text`. Anyways, I suggest to add `Python version:` to the issue template.

**Comment by Alir3z4** [comment]
@theSage21 yeah.
I've removed the `bug` label.

@matiskay Thanks for the suggestion.
