### ISSUE TITLE
Table cells are not padded

### ISSUE THREAD

**Issue by Changaco** [Alir3z4/html2text#125]
It'd be nice if tables were rendered in a human-friendly way.

- Version by `html2text --version`: 2016.4.2
- Test script:

```python
html2text("""
<table>
    <tr><th>Column #1 <th>Column #2</tr>
    <tr><td>0         <td>foo</tr>
    <tr><td>1         <td>x</tr>
</table>
""")
```

Output:

```
Column #1 | Column #2  
---|---  
0 | foo  
1 | x
```

Desired output:

```
Column #1 | Column #2
----------|----------
0         | foo
1         | x
```

- Python version `python --version`: 2.7.11

**Comment by theSage21** [comment]
I'm all for it. I'll get on this after exams.

**Comment by theSage21** [comment]
Now, getting this to work with the parser is turning out to be a pain. I propose we just pad tables after everything is done. It might impact speed since we will be iterating over the text once again.  
 @Alir3z4 @Changaco any other caveats that you can see to this approach? If nothing comes up I'm implementing this as an option to avoid breaking backward compatibility for now.

**Comment by theSage21** [comment]
@Alir3z4 @Changaco I've added padding as an option to maintain back-compatible behavior.
