### ISSUE TITLE
html2text does not work on the domain toysrus.com

### ISSUE THREAD

**Issue by priyaven** [Alir3z4/html2text#133]
html2text does not seem to parse the site toysrus.com accurately. 

example link: html2text http://www.toysrus.com/product/index.jsp?productId=45631456&prodFindSrc=prodCrossSell

expected output: text including title, price, specifications, etc. 
received output: 
trusJspVariables = window.trusJspVariables || {}; if(typeof
deconcept=="undefined") document.write('<script
src="/include/swfobject.js"><\/script>');

Please let me know if this is fixed in a future version, or if there are workarounds to ensure a better output. 
- Version by `html2text 2016.4.2`
- Test script
html2text http://www.toysrus.com/product/index.jsp?productId=45631456&prodFindSrc=prodCrossSell

- Python version `python 2.7.10`

**Comment by theSage21** [comment]
I'm having trouble pinning down the problem. I'll let you know as soon as I can.

**Comment by theSage21** [comment]
@priyaven this is being caused by the presence of `script` elements inside of `document.write` JS. I suspect something but it is too soon to say. In the mean while, running a `html.replace('script', 'blah')` before passing it to the `html2text` program seems to get the desired text.  
As a command line option this works. `curl -s http://www.toysrus.com/product/index.jsp?productId=45631456\&prodFindSrc=prodCrossSell | sed 's/script/blah/g` |html2text -`

**Comment by gilessbrown** [comment]
This line:
    https://github.com/Alir3z4/html2text/blob/master/html2text/__init__.py#L734
is the culprit.  It finds the '/script>' inside the document.write stuff and we end up with a negative `self.quiet` which means that it ends up with outputting the wrong stuff.
What is the purpose of this line?  It looks like kinda kudge-ey (if I may be so bold).

**Comment by gilessbrown** [comment]
And I've just tried the tests and none of them fail if you remove those two lines.
And it works on the toysrus.com example.
I think I'll submit a pull request.

**Comment by theSage21** [comment]
Ah, sorry for the silence @gilessbrown . We were experiencing an internet outage here. The PR looks good.
