### ISSUE TITLE
links with query string parameters come out with semi colons

### ISSUE THREAD

**Issue by therumbler** [Alir3z4/html2text#148]
e.g.

```
html_content = """

    Clone from Git Repository

    Clone the repository from <a href="http://verify.supteam.net/registrant/?verification_id=4676787&key=d8kdjKX6QJ&rid=15314">
        http://verify.supteam.net/registrant/?verification_id=4676787&key=d8kdjKX6QJ&rid=15314
    </a>

"""
decoder = HTMLDecoder()
text = decoder.convert_html_to_text(html_content)
print text
```

Response is [ http://verify.supteam.net/registrant/?verification_id=4676787&amp;key;=d8kdjKX6QJ&amp;rid;=15314 ](http://verify.supteam.net/registrant/?verification_id=4676787&key=d8kdjKX6QJ&rid=15314)

(note the "&amp;rid;=")

**Comment by ciprianmiclaus** [comment]
HTMLParser identifies &key and &rid as entityrefs incorrectly.
See this bug report: https://mail.python.org/pipermail/python-bugs-list/2002-March/010575.html
In entityref, html2text calls name2cp and that fails and then outputs: &key; incorrectly.
I think the fix here should be that if name2cp(c) fails with KeyError, that means c is not really an entityref, so html2text should output:
"&" + c instead of "&" + c + ";"

However this will not address the situation when the parameters in the querystring match entityref keywords. e.g.
http://abc.com/?test=1&gt=3
gt is a valid entityref, that will still be encoded to &gt;

**Comment by ciprianmiclaus** [comment]
I don't think this is a bug.
The url in the text of the a tag should have been escaped, so instead of &key and &rid, I would have expected &amp;key and &amp;rid
Without escaping it, the Python's HTMLParser thinks &key and &rid are entityrefs.

HTMLParser seems to have a bug where it recognizes &foobar; and &foobar as entityref
https://mail.python.org/pipermail/python-bugs-list/2002-January/009512.html

In html2text we call name2cp when we handle entityrefs and if that fails, we build the output as:
'&' + c + ";"
Which works for &key; entityrefs but not for &key -> this is where the additional ; is coming from.

See a similar issue reported against beautiful soup: https://bugs.launchpad.net/beautifulsoup/+bug/1132612

I suggest this should be rejected as won't fix, given that the html text of the a tag should have been escaped.

**Comment by therumbler** [comment]
@ciprianmiclaus is 100% correct. Closing this issue.
