### ISSUE TITLE
Add --no-markdown option

### ISSUE THREAD

**Issue by samuelbradshaw** [Alir3z4/html2text#170]
I would like a --no-markdown option to convert HTML to plain text.

**Comment by jonathan-zageno** [comment]
Just a note that you can reasonably easy do that with the library lxml. Once you've parsed the html you can call `itertext` on any element which is an iterator over all text elements contained in that root element.

**Comment by Alir3z4** [comment]
I agree with @jonathan-zageno here.
Such thing can be easily done by lxml or any other tools that strip HTML tags.
Django web framework already has such tiny function you can look at it.

A quick note, how Tables  or definitions lists can be converted to plain text ?

**Comment by samuelbradshaw** [comment]
I was mostly able to get what I needed using these options. Thanks!

h = html2text.HTML2Text()
h.unicode_snob = 1
h.ignore_emphasis = True
h.single_line_break = True

**Comment by jeremydouglass** [comment]
Because this is repeatedly revisited both here and on the original repo:

For people looking for *plain text* as opposed to markdown text specifically, one option is to instead use pandoc.

-   Live demo: [Try Pandoc: HTML --> plain text](https://pandoc.org/try/?text=%3Ch1%3EHeading+1%3C%2Fh1%3E%0A%3Cp%3EA+paragraph+with+%3Cem%3Eemphasis%3C%2Fem%3E+and+%3Cstrong%3Ebold%3C%2Fstrong%3E.%3C%2Fp%3E%0A%3Ch2%3EHeading+2%3C%2Fh2%3E%0A%3Ch3%3EHeading+3%3C%2Fh3%3E%0A%3Cp%3E...unordered+lists%3A%3C%2Fp%3E%0A%3Cul%3E%0A++%3Cli%3Ealpha%3C%2Fli%3E%0A++%3Cli%3Ebeta%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3E...ordered+lists%3A%3C%2Fp%3E%0A%3Col%3E%0A++%3Cli%3Edelta%3C%2Fli%3E%0A++%3Cli%3Egamma%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cp%3E...a+block+quotation%3C%2Fp%3E%0A%3Cblockquote%3ELorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit%2C+sed+do+eiusmod+tempor+incididunt+ut+labore+et+dolore+magna+aliqua.+Ut+enim+ad+minim+veniam%2C+quis+nostrud+exercitation+ullamco+laboris+nisi+ut+aliquip+ex+ea+commodo+consequat.%3C%2Fblockquote%3E%0A%3Cp%3E...and+a+table%3A%3C%2Fp%3E%0A%3Ctable%3E%0A++%3Cthead%3E%0A++++%3Ctr%3E%0A++++++++%3Cth%3E%3C%2Fth%3E%0A++++++++%3Cth%3EA%3C%2Fth%3E%0A++++++++%3Cth%3EB%3C%2Fth%3E%0A++++%3C%2Ftr%3E%0A++%3C%2Fthead%3E%0A++%3Ctbody%3E%0A++++%3Ctr%3E%0A++++++++%3Ctd%3E1%3C%2Ftd%3E%0A++++++++%3Ctd%3Ealpha%3C%2Ftd%3E%0A++++++++%3Ctd%3Ebeta%3C%2Ftd%3E%0A++++%3C%2Ftr%3E%0A++++%3Ctr%3E%0A++++++++%3Ctd%3E2%3C%2Ftd%3E%0A++++++++%3Ctd%3Elorem%3C%2Ftd%3E%0A++++++++%3Ctd%3Eipsum%3C%2Ftd%3E%0A++++%3C%2Ftr%3E%0A++%3C%2Ftbody%3E%0A%3C%2Ftable%3E&from=html&to=plain&standalone=0)

...using a command like:

```
pandoc input.html -t plain -o output.txt
```

This eliminates most formatting marks like `#` and `*` and `~` while preserving functionality like basic table layout.

Input html:

```
<h1>Heading 1</h1>
<p>A paragraph with <em>emphasis</em> and <strong>bold</strong>.</p>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<p>...unordered lists:</p>
<ul>
  <li>alpha</li>
  <li>beta</li>
</ul>
<p>...ordered lists:</p>
<ol>
  <li>delta</li>
  <li>gamma</li>
</ol>
<p>...a block quotation</p>
<blockquote>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</blockquote>
<p>...and a table:</p>
<table>
  <thead>
    <tr>
        <th></th>
        <th>A</th>
        <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>1</td>
        <td>alpha</td>
        <td>beta</td>
    </tr>
    <tr>
        <td>2</td>
        <td>lorem</td>
        <td>ipsum</td>
    </tr>
  </tbody>
</table>
```

Output plain text:

```
Heading 1

A paragraph with emphasis and bold.

Heading 2

Heading 3

...unordered lists:

-   alpha
-   beta

...ordered lists:

1.  delta
2.  gamma

...a block quotation

  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
  minim veniam, quis nostrud exercitation ullamco laboris nisi ut
  aliquip ex ea commodo consequat.

...and a table:

      A       B
  --- ------- -------
  1   alpha   beta
  2   lorem   ipsum
```

**Comment by bjd-pfq** [comment]
Thank you. I will definitely give it a go. Looks promising AND delivering. ;-)
