### ISSUE TITLE
parallel html2text

### ISSUE THREAD

**Issue by christophered** [Alir3z4/html2text#204]
Hi there,
I have a folder that contains a large number of `.html` files, and able to run `html2text` on all files using:
```
for file in *.html; do html2text "$file" > "$file.txt"; done
```

But how can I run `parallel` on such command, so that I have multiple instances of `html2text`?
@Alir3z4

**Comment by Alir3z4** [comment]
Thanks for the question.
You may be able to just 

```bash
# for file in *.html; do html2text "$file" > "$file.txt &"; done
```
To make them run in the background but obviously that would eat your RAM and CPU since it will spin up html2text instances for each file at the same time.

What I can suggest is to use the library itself with multiprocessing or multi thread.
You may find below resources a good place to look into:

* https://pymotw.com/2/multiprocessing/basics.html
* https://docs.python.org/2/library/multiprocessing.html

It should be pretty straightforward.
Let me know how it goes

**Comment by christophered** [comment]
I am working on a large number of files, and frankly it's somewhat a nightmare to try to clean those files.
Parallel is capable of cutting the time into half using my modest resources but still many hours.
I don't think multiprocessing would make a change, atleast I never tested such thing before.
https://stackoverflow.com/questions/51184001/run-html2text-using-parallel

**Comment by Alir3z4** [comment]
I see, thanks for sharing the SO thread.

I have used `html2text` for processing a sum up of ~4 millions items, although they weren't files, they were being pulled over the network from multiple sources. In the case, I've used Celery for processing background tasks and it wouldn't take more than ~2-3 minutes to get done, to be honest the blocking was actually was IO by network operations (pulling data from the APIs).

`Parallel` is a good choice, however if you need more control and much better performance, instead of calling the html2text cli directly, simply use the library directly with either a background task processing library or multi processing lib of standard library.

**Comment by christophered** [comment]
> What I can suggest is to use the library itself with multiprocessing or multi thread.

> simply use the library directly with either a background task processing library or multi processing lib of standard library.

@Alir3z4 Can you help me with `multiprocessing`, how can I use `html2text` on it?
My current command that I use is:
`find . -type f -name \*html > list.txt`
`parallel --a list.txt -j 3 'html2text {} > {.}.txt'`
