### ISSUE TITLE
Ordering issue with emphasis output

### ISSUE THREAD

**Issue by alethiophile** [Alir3z4/html2text#26]
html2text turns input of the form

    <i>weird </i>whitespace

into output of form

    _weird _whitespace

This isn't valid Markdown (or rather, it just leaves the underscores literal rather than translating them back); it seems reasonable that the output should instead be of the form

    _weird_ whitespace

Similarly, input like

    <i>inside</i>word

turns into

    _inside_word

also not valid. I think the best usage here is to leave it literal, which is valid Markdown and readable.

**Comment by theSage21** [comment]
Entering the generated markdown [here](http://markdownlivepreview.com/) gets the expected look.
Markdown is an editing format. The ultimate goal is to obtain HTML form it. `_some _word converts perfectly to HTML.

`<i>wierd </i>whitespace` should be rendered as `_wierd _whitespace` since the space is inside the <i> tag.
The space after `wierd` is also italicized. Since this is keeps us from losing info about the whitespace after the word, I feel it is a good thing and should not be removed.

**Comment by theSage21** [comment]
@Alir3z4 Close this issue? Or are you keeping this open for future references? In that case how about adding a `solved` label or something like that?
