### ISSUE TITLE
Malformed output of links

### ISSUE THREAD

**Issue by barsch** [Alir3z4/html2text#61]
```python
>>> import html2text
>>> h = html2text.HTML2Text()
>>> h.handle('<a href="http://www.test.com">http://www.test.com</a>')  #  this fails
u'<http://www.test.com>\n\n'
>>> h.handle('<a href="http://www.test.com/">http://www.test.com</a>')  # adding slash works
u'[http://www.test.com](http://www.test.com/)\n\n'
```
while this works as expected

```python
>>> h.handle('<a href="http://www.test.com/">test</a>')
u'[test](http://www.test.com/)\n\n'
>>> h.handle('<a href="http://www.test.com">test</a>')
u'[test](http://www.test.com)\n\n'
```

**Comment by theSage21** [comment]
Just started using this. working on it.

**Comment by theSage21** [comment]
@Alir3z4 @barsch Am I right in assuming that 

    <a href="http://www.test.com">http://www.test.com</a>
should give me 
    `[http://www.test.com](http://www.test.com)`

I am a little new to markdown.

**Comment by Alir3z4** [comment]
@theSage21 That is correct, `<a href="http://www.test.com">http://www.test.com</a>` should give `[http://www.test.com](http://www.test.com)`

**Comment by theSage21** [comment]
@Alir3z4 Also. Should I add some documentation? As a non English speaker this repo was very confusing to me initially. Docs would have helped.

**Comment by Alir3z4** [comment]
@theSage21 Sure, that would be great.
You can have #39 this one as well if you like.

**Comment by theSage21** [comment]
@Alir3z4 Al right. I will try to fix this then #39

**Comment by Alir3z4** [comment]
Awesome ;)

**Comment by theSage21** [comment]
This is triggered whenever the text matches the url and is an absolute url.
It seems this is deliberate. Lines 698 to 701

![delibrate code](https://cloud.githubusercontent.com/assets/7693265/7901897/8e421a28-07bd-11e5-9f27-48a7dae28fb5.png)

Removing that condition fixes it. I am not sure if this is a requirement of markdown or not. @Alir3z4 @barsch .

**Comment by theSage21** [comment]
@Alir3z4 @barsch This is not a bug. The test/url-escaping.md specifically tests this functionality. I recommend that this issue be closed.

**Comment by barsch** [comment]
Is ```<http://www.test.com>``` a valid Markdown syntax for an inline link? 

http://daringfireball.net/projects/markdown/syntax#link states:

```Markdown supports two style of links: inline and reference.
In both styles, the link text is delimited by [square brackets].```

However there is an example further down using angle brackets for a referenced links ...

```
[id]: <http://example.com/>  "Optional Title Here"
```

**Comment by theSage21** [comment]
In the tests directory the url-escaping.md file has
`* Use automatic links like <http://example.com/> when the URL is the label`
Since this type of conversion has been specifically tested I think it was intended to be a feature.

Also notice that
`<a href="http://www.test.com">http://www.test.com</a>`
`<a href="http://www.test.com/">http://www.test.com/</a>`
both translate validly to:
`<http://www.test.com>`
`<http://www.test.com/>`

Hence whenever the href is absolute and is the same as the text the format of `<http://text>` is used.

**Comment by theSage21** [comment]
@barsch @Alir3z4 How about we add a config parameter which is by default left to use automatic links but can be set to translate these types of links to normal Markdown? I think that is a good idea since people can configure as they wish then and people already depending on this module can go on undisturbed.

**Comment by Alir3z4** [comment]
@theSage21 I like the idea of having config for those kind of link. is `--reference-link` option does it ?

**Comment by theSage21** [comment]
@Alir3z4 Sorry, just noticed it. Yes `--reference-link` does it.

**Comment by Alir3z4** [comment]
@theSage21 So this issue can be closed if we consider `` --reference-link`` as the solution ?

**Comment by theSage21** [comment]
@Alir3z4 Yes. The issue can be closed. Automatic links are now optional via the `--reference-link` option.
