### ISSUE TITLE
install instructions out of date

### ISSUE THREAD

**Issue by laura-dietz** [Alir3z4/html2text#83]
The install instructions say to use

$ pip install html2text

that only gets the Aaron's old version
$ html2markdown --version
html2markdown 3.200.3

Suggestion: Remove instructions from README.md ?

**Comment by theSage21** [comment]
Can  `$ html2markdown --version` possibly be an old version of html2text?
I have this on my machine.
 ```
$ pip install html2text
$ html2text --version
html2text 2015.6.21
```

**Comment by laura-dietz** [comment]
Oh hmm .. you might be right. My system is in an unknown state because I 
- installed with with apt-get
- removed it with apt-get
- installed it with pip
(that is where this issue is from)
- uninstalled it with pip
- installed it with setup.py

It works under html2text - but there is still an out-of-date trace on my system leading to html2markdown into the wrong version.

For reference, the content of html2markdown is the following ... in case someone knows what is going on.


          #!/usr/bin/python
          # EASY-INSTALL-ENTRY-SCRIPT: 'html2text==3.200.3','console_scripts','html2text'
          __requires__ = 'html2text==3.200.3'
          import sys
          from pkg_resources import load_entry_point

          if __name__ == '__main__':
          sys.exit(
            load_entry_point('html2text==3.200.3', 'console_scripts', 'html2text')()
          )


If no one knows, feel free to mark it as "won't fix"

**Comment by Alir3z4** [comment]
Not sure why you're getting this and why pip would install an old version.
I'm using html2text in bunch of other software and the build is everyday and never failed for  such a behavior.

Since it's related to Debian based @stefanor might be helpful and right person to reach for since packages on Debian based are slightly old.

Anyway, I'm going to close this an `wont-fix` and `invalid`.

@laura-dietz Thanks for the report.
@theSage21 Thank you for your quick follow up.

**Comment by laura-dietz** [comment]
I think it is leftover from the apt-get uninstall

**Comment by theSage21** [comment]
@laura-dietz Did you try to install in a clean virtualenv? That should clear up any issues about what goes in the current installation. As for the rest, I cannot say.
