### ISSUE TITLE
Parse Code with html2text

### ISSUE THREAD

**Issue by CosmaVito** [Alir3z4/html2text#96]
I want to parse this post from Quora or a generic post with code.
For example this: http://qr.ae/Rkplrt

Through a practice of Selenium ( a library of Python ), i can get the hmtl inside of the post. In this way:
 
     h = html2text.HTML2Text()
     content = ans.find_element_by_class_name('inline_editor_value')
     html_string = content.get_attribute('innerHTML')
     text = h.handle(html_string)
     print text

I would take it all as a single text . But in the case of those tables that contain code, html2text inserts many " / n" and it not handles the indices of the rows.

So i can see this:
https://imageshack.com/i/paEKbzT4p (This is the principal div that contain the table with code)
https://imageshack.com/i/hlIxFayop (The text that html2text extract)
https://imageshack.com/i/hlHFBXvQp (Instead this is the final print of the text, with the problem of index rows and the more "\n")

That said, someone would know tell me how to set html2text in this case ?
Thank you

**Comment by theSage21** [comment]
I will get to this as soon as i have Internet and a computer.

**Comment by theSage21** [comment]
the `--bypass-tables` option might work for you. Though I cannot say for sure. Code is supposed to be put in `<code> ... </code>` tags, which is not the case here. Check if this works.

```
 h = html2text.HTML2Text()
 h.bypass_tables = True
 content = ans.find_element_by_class_name('inline_editor_value')
 html_string = content.get_attribute('innerHTML')
 text = h.handle(html_string)
 print text
```

**Comment by CosmaVito** [comment]
I had already tried that setting, but without success. In fact they remain the " / n" and are new tags.
I see this:
https://imageshack.com/i/hlhj1ZCtp

**Comment by theSage21** [comment]
Ok. After some tinkering, I present my view.

Using the html table provided at <http://www.w3schools.com/html/html_tables.asp> I obtained the following MD from html2text.

```
Number | First Name | Last Name | Points
---|---|---|---
1 | Eve | Jackson | 94
2 | John | Doe | 80
3 | Adam | Johnson | 67
4 | Jill | Smith | 50
```
Which tis rendered by Github as 

Number | First Name | Last Name | Points
---|---|---|---
1 | Eve | Jackson | 94
2 | John | Doe | 80
3 | Adam | Johnson | 67
4 | Jill | Smith | 50


Now, the html provided by Quora for code is at

<https://www.quora.com/What-is-the-most-complex-line-of-C-code-you-have-created-or-encountered/answer/Saad-Lulu-1?srid=QJ75&share=1>

The raw html under question is:

```
<tbody><tr><td class="linenos"><pre>1
2
3
4
5
6
7
</pre>
</td><td class="code">

<div class="codeblock">
<pre><span class="">#include &lt;stdio.h&gt;<br></span></pre></div>

<div class="codeblock"><pre><span class=""><br></span></pre></div>

<div class="codeblock"><pre><span class="">int v,i,j,k,l,s,a[99];<br></span></pre></div>

<div class="codeblock"><pre><span class="">main()<br></span></pre></div>

<div class="codeblock"><pre><span class="">{<br></span></pre></div>

<div class="codeblock"><pre><span class="">		for(scanf("%d", &amp;s);*a-s;v=a[j*=v]-a[i],k=i&lt;s,j+=(v=j&lt;s&amp;&amp;(!k&amp;&amp;!!printf(2+"\n\n%c"-(!l&lt;&lt;!j)," #Q"[l^v?(l^j)&amp;1:2])&amp;&amp;++l||a[i]&lt;s&amp;&amp;v&amp;&amp;v-i+j&amp;&amp;v+i-j))&amp;&amp;!(l%=s),v||(i==j?a[i+=k]=0:++a[i])&gt;=s*k&amp;&amp;++a[--i]);<br></span></pre></div>

<div class="codeblock"><pre><span class="">}<br></span></pre></div>

</td></tr></tbody>
```

This generates the MD provided by @CosmaVito . Namely:

```
\n    1\n    2\n    3\n    4\n    5\n    6\n    7\n\n|\n\n    \n    \n                        #include <stdio.h>\n                          \n    \n        \n        \n    \n    \n                        \n                          \n    \n        \n        \n    \n    \n                        int v,i,j,k,l,s,a[99];\n                          \n    \n        \n        \n    \n    \n                        main()\n                          \n    \n        \n        \n    \n    \n                        {\n                          \n    \n        \n        \n    \n    \n                        \t\tfor(scanf("%d", &s);*a-s;v=a[j*=v]-a[i],k=i<s,j+=(v=j<s&&(!k&&!!printf(2+"\\n\\n%c"-(!l<<!j)," #Q"[l^v?(l^j)&1:2])&&++l||a[i]<s&&v&&v-i+j&&v+i-j))&&!(l%=s),v||(i==j?a[i+=k]=0:++a[i])>=s*k&&++a[--i]);\n                          \n    \n        \n        \n    \n    \n                        }\n                          \n    \n        \n          \n  \n---|---\n\n
```

On some careful inspection one can see that the generated `\n` are consistent with the `pre`, `span`, `div` and `br` tags in the html. For example the last `}` is preceeded by 7 `\n`. these are consistent with the html.

I find no fault with html2text. As for the problem, @CosmaVito you might want to clean the HTML a little before feeding it to html2text since standards are not being followed. As [mentioned by W3C](http://www.w3schools.com/tags/tag_code.asp), code should be put inside `<code> ... </code>`.

For html that does not follow standards, I find [Beautiful Soup](http://www.crummy.com/software/BeautifulSoup/) to be wonderful.
